//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherServiceTryIt.FlightReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FlightReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCityCodes", ReplyAction="http://tempuri.org/IService1/getCityCodesResponse")]
        string[] getCityCodes(string origin, string destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCityCodes", ReplyAction="http://tempuri.org/IService1/getCityCodesResponse")]
        System.Threading.Tasks.Task<string[]> getCityCodesAsync(string origin, string destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchFlights", ReplyAction="http://tempuri.org/IService1/searchFlightsResponse")]
        string[] searchFlights(string origin, string destination, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchFlights", ReplyAction="http://tempuri.org/IService1/searchFlightsResponse")]
        System.Threading.Tasks.Task<string[]> searchFlightsAsync(string origin, string destination, string date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WeatherServiceTryIt.FlightReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WeatherServiceTryIt.FlightReference.IService1>, WeatherServiceTryIt.FlightReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getCityCodes(string origin, string destination) {
            return base.Channel.getCityCodes(origin, destination);
        }
        
        public System.Threading.Tasks.Task<string[]> getCityCodesAsync(string origin, string destination) {
            return base.Channel.getCityCodesAsync(origin, destination);
        }
        
        public string[] searchFlights(string origin, string destination, string date) {
            return base.Channel.searchFlights(origin, destination, date);
        }
        
        public System.Threading.Tasks.Task<string[]> searchFlightsAsync(string origin, string destination, string date) {
            return base.Channel.searchFlightsAsync(origin, destination, date);
        }
    }
}
